name: Deploy develop

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Process default to deploy
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/develop' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Using nodejs
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install packages
        run: yarn install

      - name: Deploy serverless
        uses: serverless/github-action@v3.1
        with:
          args: deploy --stage dev --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DB_CONNECTION: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          RSA_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}
          SECRET_JWE: ${{ secrets.SECRET_JWE }}
